### ISSUE TITLE
[p]automod antispam does not work properly (does not take any action)

### ISSUE THREAD

**Issue by Skyridr** [retke/Laggrons-Dumb-Cogs#82] opened 2020-06-22 09:26 UTC
See: https://github.com/retke/Laggrons-Dumb-Cogs/issues/86

Reason why it wasn't working is because of mute being broken. Though, automod also started breaking after this: 

https://github.com/retke/Laggrons-Dumb-Cogs/issues/85

**Comment by laggron42** [comment] 2020-07-02 09:27
Both of the mentioned issues are resolved. Consider updating this by either closing if this is fixed, or providing more details (check `warnsystem.log`).

**Comment by laggron42** [comment] 2021-03-03 15:55
Can't reproduce, code changed much since then, I feel like this issue is outdated now. Feel free to repoen if necessary.

**Closed as completed by laggron42** 2021-03-03 15:55 UTC
Labels: Type: Bug, Status: Needs testing, Status: Needs discussion, Cog: WarnSystem
